language: elixir
cache:
  directories:
    - deps
    - _build
matrix:
  include:
    - elixir: 1.11.2
      otp_release: 23.0
      env: MIX_EXS=ci/mix-ecto-3.0.exs
    - elixir: 1.10.4
      otp_release: 22.3
      env: MIX_EXS=ci/mix-ecto-3.0.exs
    - elixir: 1.9.4
      otp_release: 22.3
      env: MIX_EXS=ci/mix-ecto-3.0.exs
    - elixir: 1.8.2
      otp_release: 22.3
      env: MIX_EXS=ci/mix-ecto-3.0.exs
    - elixir: 1.7.4
      otp_release: 22.3
      env: MIX_EXS=ci/mix-ecto-3.0.exs
    - elixir: 1.6.6
      otp_release: 20.3
      env: MIX_EXS=ci/mix-ecto-2.2.exs
    - elixir: 1.6.6
      otp_release: 20.0
      env: MIX_EXS=ci/mix-ecto-2.2.exs
    - elixir: 1.5.3
      otp_release: 19.3
      env: MIX_EXS=ci/mix-ecto-2.2.exs
    - elixir: 1.5.3
      otp_release: 19.0
      env: MIX_EXS=ci/mix-ecto-2.1.exs
    - elixir: 1.4.5
      otp_release: 18.3
      env: MIX_EXS=ci/mix-ecto-2.0.exs
after_success:
  - mix bench
